[package]
name = "shadertoy_viewer"
version = "0.1.0"
authors = ["Johan Andersson <repi@repi.se>"]

[dependencies]
floating-duration = "0.1.1"
reqwest = "0.8.2"
json = "0.11.12"
rayon = "0.9.0"
clap = "2.29.0"
spirv_cross = "0.4.3"
shaderc = "0.3.3"