[package]
name = "shadertoy_viewer"
version = "0.1.0"
authors = ["Johan Andersson <repi@repi.se>"]
homepage = "https://github.com/repi/shadertoy_viewer"
repository = "https://github.com/repi/shadertoy_viewer"
readme = "README.md"
license = "MIT/Apache-2.0"
keywords = ["shaders", "shadertoy", "render", "mac", "metal"]
categories = ["rendering"]

[dependencies]
floating-duration = "0.1.1"
chrono = "0.4.0"
reqwest = "0.8.2"
json = "0.11.12"
rayon = "0.9.0"
clap = "2.29.0"
spirv_cross = "0.4.3"
shaderc = "0.3.3"
serde = "1.0.26"
serde_json = "1.0.8"
serde_derive = "1.0.26"
winit = "0.10.0"
cocoa = "0.13.0"
objc-foundation = "0.1.1"
objc = "0.2.2"
libc = "0.2.34"
foreign-types = "0.3.2"
metal-rs = { git = "https://github.com/repi/metal-rs", branch = "border-color" }
rust-base58 = "0.0.4"
shadertoy = { path = "src/shadertoy", version = "0.1.0" }
