[package]
name = "shadertoy-browser"
version = "0.2.1"
authors = ["Johan Andersson <repi@repi.se>"]
repository = "https://github.com/repi/shadertoy_viewer"
readme = "README.md"
license = "MIT/Apache-2.0"
keywords = ["shaders", "shadertoy", "render", "mac", "metal"]
categories = ["rendering"]

[badges]
travis-ci = { repository = "repi/shadertoy-browser" }

[workspace]
members = [
    "src/shadertoy"
]

[dependencies]
floating-duration = "0.1.1"
chrono = "0.4.0"
reqwest = "0.8.2"
rayon = "0.9.0"
clap = "2.29.0"
spirv_cross = "0.4.3"
shaderc = "0.3.3"
serde = "1.0.26"
serde_json = "1.0.8"
winit = "0.10.0"
libc = "0.2.34"
foreign-types = "0.3.2"
rust-base58 = "0.0.4"
shadertoy = { path = "src/shadertoy", version = "0.1.1" }

[target.'cfg(target_os = "macos")'.dependencies]
cocoa = "0.13.0"
objc = "0.2.2"
objc-foundation = "0.1.1"
metal-rs = { git = "https://github.com/gfx-rs/metal-rs.git", branch = "master" }
