[package]
name = "shadertoy"
version = "0.1.0"
authors = ["Johan Andersson <repi@repi.se>"]
repository = "https://github.com/repi/shadertoy_viewer/src/shadertoy"
readme = "README.md"
license = "MIT/Apache-2.0"
keywords = ["shaders", "shadertoy", "render", "mac", "metal"]
categories = ["rendering"]

[dependencies]
reqwest = "0.8.2"
json = "0.11.12"
serde = "1.0.24"
serde_json = "1.0.8"
serde_derive = "1.0.25"
