[package]
name = "shadertoy"
version = "0.1.0"
authors = ["Johan Andersson <repi@repi.se>"]

[dependencies]
reqwest = "0.8.2"
json = "0.11.12"
serde = "1.0.24"
serde_json = "1.0.8"
serde_derive = "1.0.25"
